# Generated by Django 2.2.16 on 2022-07-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('user', 'Аутентифицированный пользователь'), ('admin', 'Адмитнистратор'), ('moderator', 'Модератор')], default='user', verbose_name='Роль'),
        ),
    ]
