# Generated by Django 2.2.16 on 2022-08-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220805_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('user', 'Аутентифицированный пользователь'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='user', verbose_name='Роль'),
        ),
    ]
