# Generated by Django 2.2.16 on 2022-07-28 19:15

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220728_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(validators=[reviews.models.validate_year]),
        ),
        migrations.AddConstraint(
            model_name='titles',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='unique_name_year'),
        ),
    ]
