# Generated by Django 2.2.16 on 2022-08-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220802_1514'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='title_one_review',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_review'),
        ),
    ]
