# Generated by Django 2.2.16 on 2022-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220728_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
