# Generated by Django 2.2.16 on 2022-07-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220729_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
