# Generated by Django 2.2.16 on 2022-07-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220729_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='genretitles',
            constraint=models.UniqueConstraint(fields=('genre', 'title'), name='unique_genre_title'),
        ),
    ]
